### ISSUE TITLE
Error: no reference found for shorthand 'origin/HEAD'

### ISSUE THREAD

**Issue by BerkeleyTrue** [nickgerace/gfold#202]
After updating to 4.0 recently I started experiencing this issue.

Error: no reference found for shorthand 'origin/HEAD'; class=Reference (4); code=NotFound (-3)

![image](https://user-images.githubusercontent.com/6775919/167979370-18a0410e-a365-4317-804d-8bdb42b64bb6.png)

Downgrading back to 3.0 doesn't show the same issue
![image](https://user-images.githubusercontent.com/6775919/167980108-283c248e-9a87-458a-b5bf-cfb52145ff25.png)

I saw there was a PR for a similar issue that was merged in quite some time ago. Did that not make it into the new release?

**Comment by nickgerace** [comment]
Ah yes, I thought it had been fixed with #192 or another issue that I am not recalling at the moment. Thanks for filing the issue; I'll look into it.

Would you mind running with `RUST_LOG=debug RUST_BACKTRACE=1 gfold`? Please feel free to redact any sensitive information, though I doubt that'll be the case.

**Comment by BerkeleyTrue** [comment]
@nickgerace Here is the output in a gist

https://gist.github.com/BerkeleyTrue/b9699f9dbd27e6b11e71ce57b314d2a6

Please let men kno

**Comment by AckslD** [comment]
I'm also still seeing this issue when the remote is something else then `origin`.

**Comment by nickgerace** [comment]
Thank you @BerkeleyTrue and @AckslD. I'll add this bug to the integration test payload and see what I can do.

**Comment by AckslD** [comment]
@nickgerace I made an attempt to add a failing test reproducing this in #210. My rust skills are not very high but I hope it can help to find the underlying issue :)

**Comment by nickgerace** [comment]
Merged #202 and going to look further. CI needs to catch this as well if it does not.

**Comment by nickgerace** [comment]
Thank to @AckslD's PR, I think I figured it out.

The app tries to determine if a repository with its current checked out branch is "unpushed" by checking if the local branch has a corresponding remote. If if does, then we check if the commits match. If it doesn't then we assume that the state is "unpushed". The problem here was in the latter check. During that check, we try to resolve the reference with a given short name, but we would _fail_ if we could not. Well, if a remote branch doesn't exist with that short name (e.g. `origin/HEAD`), then we will _always fail_, which is undesired behavior. I believe #215 _should_ solve the issue.

**Comment by AckslD** [comment]
Thanks @nickgerace, things seem to indeed work now for me :)

**Comment by nickgerace** [comment]
Glad to hear!
